### ISSUE TITLE
Fel i tarning()

### ISSUE THREAD

**Issue by deskavaenkelt** [deskavaenkelt/java_inl-mningsuppgift1_g#1]
"C:\Program Files\Java\jdk-10.0.2\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2\lib\idea_rt.jar=51466:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2\bin" -Dfile.encoding=UTF-8 -classpath C:\git\java_inl-mningsuppgift1_g\out\production\java_inl-mningsuppgift1_g com.inlamniongsuppgift1.InlamningsUppgift1
Skriv in ditt namn: Lars
Hej Lars du kommer att spela mot Datorn. 
Välj antal kast som ska spelas: 5
Kast 1 gav: 6
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
Kast 2 gav: 6
Kast 3 gav: 2
Kast 4 gav: 2
	at com.inlamniongsuppgift1.InlamningsUppgift1.tarning(InlamningsUppgift1.java:51)
	at com.inlamniongsuppgift1.InlamningsUppgift1.main(InlamningsUppgift1.java:21)

Process finished with exit code 1

**Comment by deskavaenkelt** [comment]
åtgärdat
